-- Catalogue complet (grille de prix officielle) + personnalisation. Met à jour / ajoute, ne supprime rien.
-- Le stock n'est plus géré (null).
insert into armurerie_products (id, name, category, price, stock, image) values
  ('rev-cattleman', 'Revolver Cattleman', 'Revolvers', 74.5, null, 'img/items/rev-cattleman.png'),
  ('rev-cattleman-mex', 'Cattleman mexicain', 'Revolvers', 69, null, 'img/items/rev-cattleman-mex.png'),
  ('rev-double', 'Revolver Double-Action', 'Revolvers', 51.5, null, 'img/items/rev-double.png'),
  ('rev-lemat', 'Revolver LeMat', 'Revolvers', 63, null, 'img/items/rev-lemat.png'),
  ('rev-navy', 'Revolver Navy', 'Revolvers', 16.5, null, 'img/items/rev-navy.png'),
  ('rev-schofield', 'Revolver Schofield', 'Revolvers', 57.5, null, 'img/items/rev-schofield.png'),
  ('pis-mauser', 'Pistolet Mauser', 'Pistolets', 34.5, null, 'img/items/pis-mauser.png'),
  ('pis-semi', 'Pistolet semi-automatique', 'Pistolets', 63, null, 'img/items/pis-semi.png'),
  ('pis-volcanic', 'Pistolet Volcanic', 'Pistolets', 69, null, 'img/items/pis-volcanic.png'),
  ('pis-m1899', 'Pistolet M1899', 'Pistolets', 80.5, null, 'img/items/pis-m1899.png'),
  ('car-repeat', 'Carabine à répétition', 'Carabines', 68.5, null, 'img/items/car-repeat.png'),
  ('car-evans', 'Evans', 'Carabines', 86, null, 'img/items/car-evans.png'),
  ('car-henry', 'Henry', 'Carabines', 137.5, null, 'img/items/car-henry.png'),
  ('car-winchester', 'Winchester', 'Carabines', 120.5, null, 'img/items/car-winchester.png'),
  ('fus-varmint', 'Varmint', 'Fusils', 63, null, 'img/items/fus-varmint.png'),
  ('fus-bolt', 'Bolt (fusil à verrou)', 'Fusils', 189, null, 'img/items/fus-bolt.png'),
  ('fus-springfield', 'Springfield', 'Fusils', 218, null, 'img/items/fus-springfield.png'),
  ('fus-carcano', 'Carcano', 'Fusils', 558.5, null, 'img/items/fus-carcano.png'),
  ('fus-rolling', 'Rolling Block', 'Fusils', 520, null, 'img/items/fus-rolling.png'),
  ('pom-elephant', 'Fusil éléphant', 'Fusils', 269.5, null, 'img/items/pom-elephant.png'),
  ('pom-pump', 'Fusil à pompe', 'Fusils à pompe', 323.5, null, 'img/items/pom-pump.png'),
  ('pom-double', 'Double canon', 'Fusils à pompe', 378.5, null, 'img/items/pom-double.png'),
  ('pom-semi', 'Pompe semi-auto', 'Fusils à pompe', 290.5, null, 'img/items/pom-semi.png'),
  ('pom-sawed', 'Canon scié', 'Fusils à pompe', 285, null, 'img/items/pom-sawed.png'),
  ('pom-repeating', 'Pompe à répétition', 'Fusils à pompe', 269.5, null, 'img/items/pom-repeating.png'),
  ('bl-knife', 'Couteau', 'Armes de jet & blanches', 2.5, null, 'img/items/bl-knife.png'),
  ('bl-rustic', 'Couteau de skinner', 'Armes de jet & blanches', 3, null, 'img/items/bl-rustic.png'),
  ('bl-cultist', 'Couteau cultiste', 'Armes de jet & blanches', 4, null, 'img/items/bl-cultist.png'),
  ('bl-throwing', 'Couteaux de lancer', 'Armes de jet & blanches', 12.5, null, 'img/items/bl-throwing.png'),
  ('bl-hatchet', 'Hachette', 'Armes de jet & blanches', 17.5, null, 'img/items/bl-hatchet.png'),
  ('bl-machete', 'Machette', 'Armes de jet & blanches', 57, null, 'img/items/bl-machete.png'),
  ('bl-machete-coll', 'Machette de collection', 'Armes de jet & blanches', 114.5, null, 'img/items/bl-machete-coll.png'),
  ('mun-rev', 'Munitions de revolver normales', 'Munitions', 0.25, null, 'img/items/mun-rev.png'),
  ('mun-pis', 'Munitions de pistolet normales', 'Munitions', 0.25, null, 'img/items/mun-pis.png'),
  ('mun-car', 'Munitions de répétition normales', 'Munitions', 0.25, null, 'img/items/mun-car.png'),
  ('mun-varmint', 'Munitions de Varmint normales', 'Munitions', 0.25, null, 'img/items/mun-varmint.png'),
  ('mun-varmint-tranq', 'Munitions tranquillisantes de Varmint', 'Munitions', 0.25, null, 'img/items/mun-varmint-tranq.png'),
  ('mun-fus', 'Munitions de fusil normales', 'Munitions', 0.25, null, 'img/items/mun-fus.png'),
  ('mun-elephant', 'Munitions de fusil à éléphant', 'Munitions', 0.25, null, 'img/items/mun-elephant.png'),
  ('mun-pom', 'Munitions de fusil à pompe normales', 'Munitions', 0.25, null, 'img/items/mun-pom.png'),
  ('mun-knife', 'Munitions de couteaux de lancer', 'Munitions', 0.4, null, 'img/items/mun-knife.png'),
  ('mun-hatchet', 'Munitions de hachette', 'Munitions', 0.4, null, 'img/items/mun-hatchet.png'),
  ('acc-oil', 'Huile pour arme', 'Accessoires', 0.2, null, 'img/items/acc-oil.png'),
  ('acc-cuffs', 'Menottes', 'Accessoires', 1.25, null, 'img/items/acc-cuffs.png'),
  ('acc-binoculars', 'Jumelles améliorées', 'Accessoires', 2, null, 'img/items/acc-binoculars.png'),
  ('acc-lasso', 'Lasso renforcé', 'Accessoires', 5.5, null, 'img/items/acc-lasso.png'),
  ('cus-esth-poing', 'Esthétique — arme de poing', 'Personnalisation', 1.5, null, null),
  ('cus-esth-epaule', 'Esthétique — arme d''épaule', 'Personnalisation', 2, null, null),
  ('cus-lunette-petite', 'Lunette petite', 'Personnalisation', 110, null, null),
  ('cus-lunette-moyenne', 'Lunette moyenne', 'Personnalisation', 120, null, null),
  ('cus-lunette-grande', 'Lunette grande', 'Personnalisation', 140, null, null),
  ('cus-meca-1', 'Amélioration mécanique — arme 0 à 50 $', 'Personnalisation', 4.5, null, null),
  ('cus-meca-2', 'Amélioration mécanique — arme 50 à 100 $', 'Personnalisation', 7, null, null),
  ('cus-meca-3', 'Amélioration mécanique — arme 100 à 200 $', 'Personnalisation', 10, null, null),
  ('cus-meca-4', 'Amélioration mécanique — arme 200 à 300 $', 'Personnalisation', 15, null, null),
  ('cus-meca-5', 'Amélioration mécanique — arme 300 $ et plus', 'Personnalisation', 20, null, null)
on conflict (id) do update set name = excluded.name, category = excluded.category, price = excluded.price,
  stock = null, image = excluded.image;
