-- Armurerie — tables ajoutées au projet Supabase de l'EMS (préfixe armurerie_, n'affecte pas l'EMS)
-- À exécuter une fois dans Supabase > SQL Editor.
-- Accès SANS connexion : la clé publique (anon) peut lire/écrire. Choix assumé :
-- quiconque possède l'URL du site peut consulter et modifier les données.

create table if not exists armurerie_products (
  id text primary key,
  name text not null check (char_length(name) between 1 and 80),
  category text not null,
  price numeric(12,2) not null check (price >= 0),
  stock integer check (stock is null or stock >= 0),
  image text,
  created_at timestamptz not null default now()
);

create table if not exists armurerie_clients (
  id text primary key,
  name text not null check (char_length(name) between 1 and 80),
  phone text not null default '',
  license text not null default '',
  license_valid boolean not null default true,
  notes text not null default '' check (char_length(notes) <= 500),
  created_at timestamptz not null default now()
);

create table if not exists armurerie_orders (
  id text primary key,
  number bigint generated by default as identity unique,
  client_id text,
  client_name text not null,
  items jsonb not null default '[]'::jsonb,
  discount_pct numeric(5,2) not null default 0,
  tax_pct numeric(5,2) not null default 0,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  received numeric(12,2) not null default 0,
  change numeric(12,2) not null default 0,
  status text not null default 'payee' check (status in ('en_attente','payee','livree','annulee')),
  note text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists armurerie_orders_created_at_idx on armurerie_orders (created_at desc);
create index if not exists armurerie_orders_client_id_idx on armurerie_orders (client_id);

create table if not exists armurerie_settings (
  id integer primary key default 1 check (id = 1),
  shop_name text not null default 'Armurerie de Valentine',
  town text not null default 'Valentine, New Hanover',
  tax_pct numeric(5,2) not null default 0
);
insert into armurerie_settings (id) values (1) on conflict do nothing;

-- Mouvement de stock atomique (évite les conflits entre deux caisses)
create or replace function armurerie_adjust_stock(p_id text, p_delta integer)
returns void language sql security invoker as $$
  update armurerie_products set stock = greatest(0, stock + p_delta) where id = p_id and stock is not null;
$$;

-- Recale la numérotation des commandes (après import d'une sauvegarde ou remise à zéro)
create or replace function armurerie_reset_order_number()
returns void language plpgsql security definer set search_path = public as $$
begin
  perform setval(pg_get_serial_sequence('armurerie_orders', 'number'), coalesce((select max(number) from armurerie_orders), 0) + 1, false);
end $$;

-- Accès public (pas de connexion)
alter table armurerie_products enable row level security;
alter table armurerie_clients  enable row level security;
alter table armurerie_orders   enable row level security;
alter table armurerie_settings enable row level security;
do $$
declare t text;
begin
  foreach t in array array['armurerie_products','armurerie_clients','armurerie_orders','armurerie_settings'] loop
    execute format('drop policy if exists "armurerie acces public" on %I', t);
    execute format('create policy "armurerie acces public" on %I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;
grant execute on function armurerie_adjust_stock(text, integer) to anon, authenticated;
grant execute on function armurerie_reset_order_number() to anon, authenticated;

-- Temps réel : toutes les caisses voient les changements instantanément
alter publication supabase_realtime add table armurerie_products, armurerie_clients, armurerie_orders, armurerie_settings;

-- Catalogue de départ (boutique en jeu)
insert into armurerie_products (id, name, category, price, stock, image) values
  ('rev-navy', 'Revolver Navy', 'Revolvers', 16.5, 3, 'img/items/rev-navy.png'),
  ('rev-cattleman', 'Revolver Cattleman', 'Revolvers', 71.5, 0, 'img/items/rev-cattleman.png'),
  ('rev-lemat', 'Revolver Lemat', 'Revolvers', 60.5, 0, 'img/items/rev-lemat.png'),
  ('rev-double', 'Revolver Double-Action', 'Revolvers', 49.5, 0, 'img/items/rev-double.png'),
  ('pis-m1899', 'Pistolet M1899', 'Pistolets', 77, 0, 'img/items/pis-m1899.png'),
  ('pis-mauser', 'Pistolet Mauser', 'Pistolets', 33, 0, 'img/items/pis-mauser.png'),
  ('car-winchester', 'Winchester Repeater', 'Carabines', 115.5, 0, 'img/items/car-winchester.png'),
  ('fus-bolt', 'BoltAction Rifle', 'Fusils', 181.5, 0, 'img/items/fus-bolt.png'),
  ('fus-carcano', 'Carcano Rifle', 'Fusils', 535.5, 0, 'img/items/fus-carcano.png'),
  ('pom-sawed', 'Fusil à canon scié', 'Fusils à pompe', 286, 0, 'img/items/pom-sawed.png'),
  ('pom-pump', 'Fusil à pompe', 'Fusils à pompe', 309.75, 0, 'img/items/pom-pump.png'),
  ('pom-semi', 'Shotgun Semi-auto', 'Fusils à pompe', 291.5, 0, 'img/items/pom-semi.png'),
  ('bl-knife', 'Couteau', 'Armes de jet & blanches', 2.5, 7, 'img/items/bl-knife.png'),
  ('bl-merchant', 'Marchand de couteaux', 'Armes de jet & blanches', 3, 0, 'img/items/bl-merchant.png'),
  ('bl-throwing', 'Couteaux de lancer', 'Armes de jet & blanches', 12.5, 0, 'img/items/bl-throwing.png'),
  ('bl-hatchet', 'Hachette de chasse', 'Armes de jet & blanches', 15, 0, 'img/items/bl-hatchet.png'),
  ('mun-rev', 'Munitions normales — revolver', 'Munitions', 0.2, 0, 'img/items/mun-rev.png'),
  ('mun-pis', 'Munitions normales — pistolet', 'Munitions', 0.2, 0, 'img/items/mun-pis.png'),
  ('mun-fus', 'Munitions normales — fusil', 'Munitions', 0.2, 27, 'img/items/mun-fus.png'),
  ('mun-car', 'Munitions normales — carabine', 'Munitions', 0.2, 12, 'img/items/mun-car.png'),
  ('mun-pom', 'Munitions normales — fusil à pompe', 'Munitions', 0.2, 12, 'img/items/mun-pom.png'),
  ('mun-hatchet', 'Hatchet Ammo', 'Munitions', 0.4, 0, 'img/items/mun-hatchet.png'),
  ('mun-knife', 'Munitions de couteaux', 'Munitions', 0.4, 0, 'img/items/mun-knife.png'),
  ('acc-oil', 'Huile pour arme', 'Accessoires', 0.2, 29, 'img/items/acc-oil.png'),
  ('acc-lasso', 'Lasso renforcé', 'Accessoires', 5.5, 8, 'img/items/acc-lasso.png'),
  ('acc-binoculars', 'Jumelles améliorées', 'Accessoires', 2, 3, 'img/items/acc-binoculars.png')
on conflict (id) do nothing;
