-- Catalogue complet (grille de prix officielle) + personnalisation. Met à jour / ajoute, ne supprime rien.
-- Le stock n'est plus géré (null).
insert into armurerie_products (id, name, category, price, stock, image) values
  ('rev-cattleman', 'Revolver Cattleman', 'Revolvers', 71.5, null, 'img/items/rev-cattleman.png'),
  ('rev-cattleman-mex', 'Cattleman mexicain', 'Revolvers', 66, null, 'img/items/rev-cattleman-mex.png'),
  ('rev-double', 'Revolver Double-Action', 'Revolvers', 49.5, null, 'img/items/rev-double.png'),
  ('rev-lemat', 'Revolver LeMat', 'Revolvers', 60.5, null, 'img/items/rev-lemat.png'),
  ('rev-navy', 'Revolver Navy', 'Revolvers', 16.5, null, 'img/items/rev-navy.png'),
  ('rev-schofield', 'Revolver Schofield', 'Revolvers', 55, null, 'img/items/rev-schofield.png'),
  ('pis-mauser', 'Pistolet Mauser', 'Pistolets', 33, null, 'img/items/pis-mauser.png'),
  ('pis-semi', 'Pistolet semi-automatique', 'Pistolets', 60.5, null, 'img/items/pis-semi.png'),
  ('pis-volcanic', 'Pistolet Volcanic', 'Pistolets', 66, null, 'img/items/pis-volcanic.png'),
  ('pis-m1899', 'Pistolet M1899', 'Pistolets', 77, null, 'img/items/pis-m1899.png'),
  ('car-repeat', 'Répétition', 'Carabines', 66, null, 'img/items/car-repeat.png'),
  ('car-evans', 'Evans', 'Carabines', 82.5, null, 'img/items/car-evans.png'),
  ('car-henry', 'Henry', 'Carabines', 132, null, 'img/items/car-henry.png'),
  ('car-winchester', 'Winchester', 'Carabines', 115.5, null, 'img/items/car-winchester.png'),
  ('fus-varmint', 'Varmint', 'Fusils', 60.5, null, 'img/items/fus-varmint.png'),
  ('fus-bolt', 'Bolt (fusil à verrou)', 'Fusils', 181.5, null, 'img/items/fus-bolt.png'),
  ('fus-springfield', 'Springfield', 'Fusils', 209, null, 'img/items/fus-springfield.png'),
  ('fus-carcano', 'Carcano', 'Fusils', 535.5, null, 'img/items/fus-carcano.png'),
  ('fus-rolling', 'Rolling Block', 'Fusils', 498.75, null, 'img/items/fus-rolling.png'),
  ('pom-pump', 'Fusil à pompe', 'Fusils à pompe', 309.75, null, 'img/items/pom-pump.png'),
  ('pom-double', 'Double canon', 'Fusils à pompe', 362.25, null, 'img/items/pom-double.png'),
  ('pom-semi', 'Pompe semi-auto', 'Fusils à pompe', 291.5, null, 'img/items/pom-semi.png'),
  ('pom-sawed', 'Canon scié', 'Fusils à pompe', 286, null, 'img/items/pom-sawed.png'),
  ('pom-elephant', 'Fusil éléphant', 'Fusils à pompe', 330, null, 'img/items/pom-elephant.png'),
  ('pom-repeating', 'Pompe à répétition', 'Fusils à pompe', 258.5, null, 'img/items/pom-repeating.png'),
  ('bl-knife', 'Couteau', 'Armes de jet & blanches', 2.5, null, 'img/items/bl-knife.png'),
  ('bl-throwing', 'Couteaux de lancer', 'Armes de jet & blanches', 12.5, null, 'img/items/bl-throwing.png'),
  ('bl-rustic', 'Couteau rustique', 'Armes de jet & blanches', 3, null, 'img/items/bl-rustic.png'),
  ('bl-merchant', 'Couteau commerçant', 'Armes de jet & blanches', 3, null, 'img/items/bl-merchant.png'),
  ('bl-hatchet', 'Hachette de chasse', 'Armes de jet & blanches', 15, null, 'img/items/bl-hatchet.png'),
  ('bl-machete', 'Machette', 'Armes de jet & blanches', 55, null, 'img/items/bl-machete.png'),
  ('bl-machete-coll', 'Machette de collectionneur', 'Armes de jet & blanches', 110, null, 'img/items/bl-machete-coll.png'),
  ('mun-rev', 'Munitions de revolver normales', 'Munitions', 0.2, null, 'img/items/mun-rev.png'),
  ('mun-pis', 'Munitions de pistolet normales', 'Munitions', 0.2, null, 'img/items/mun-pis.png'),
  ('mun-car', 'Munitions de répétition normales', 'Munitions', 0.2, null, 'img/items/mun-car.png'),
  ('mun-varmint', 'Munitions de Varmint normales', 'Munitions', 0.2, null, 'img/items/mun-varmint.png'),
  ('mun-varmint-tranq', 'Munitions tranquillisantes de Varmint', 'Munitions', 0.2, null, 'img/items/mun-varmint-tranq.png'),
  ('mun-fus', 'Munitions de fusil normales', 'Munitions', 0.2, null, 'img/items/mun-fus.png'),
  ('mun-elephant', 'Munitions de fusil à éléphant', 'Munitions', 0.2, null, 'img/items/mun-elephant.png'),
  ('mun-pom', 'Munitions de fusil à pompe normales', 'Munitions', 0.2, null, 'img/items/mun-pom.png'),
  ('mun-knife', 'Munitions de couteaux de lancer', 'Munitions', 0.4, null, 'img/items/mun-knife.png'),
  ('mun-hatchet', 'Munitions de hachette', 'Munitions', 0.4, null, 'img/items/mun-hatchet.png'),
  ('acc-oil', 'Huile pour arme', 'Accessoires', 0.2, null, 'img/items/acc-oil.png'),
  ('acc-cuffs', 'Menottes', 'Accessoires', 1.25, null, 'img/items/acc-cuffs.png'),
  ('acc-binoculars', 'Jumelles améliorées', 'Accessoires', 2, null, 'img/items/acc-binoculars.png'),
  ('acc-lasso', 'Lasso renforcé', 'Accessoires', 5.5, null, 'img/items/acc-lasso.png'),
  ('cus-viseur', 'Viseur', 'Personnalisation', 4.5, null, null),
  ('cus-viseur-mat', 'Matériau du viseur', 'Personnalisation', 1.25, null, null),
  ('cus-lunette', 'Lunette', 'Personnalisation', 105, null, null),
  ('cus-rayure', 'Rayure du canon', 'Personnalisation', 4.5, null, null),
  ('cus-canon', 'Canon', 'Personnalisation', 4.5, null, null),
  ('cus-canon-mat', 'Matériau du canon', 'Personnalisation', 1.25, null, null),
  ('cus-canon-grav', 'Gravure du canon', 'Personnalisation', 1.25, null, null),
  ('cus-cadre-mat', 'Matériau du cadre', 'Personnalisation', 1.25, null, null),
  ('cus-cadre-grav', 'Gravure du cadre', 'Personnalisation', 1.25, null, null),
  ('cus-cadre-grav-mat', 'Matériau de la gravure du cadre', 'Personnalisation', 1.25, null, null),
  ('cus-cyl-mat', 'Matériau du cylindre', 'Personnalisation', 1.25, null, null),
  ('cus-cyl-grav', 'Gravure du cylindre', 'Personnalisation', 1.25, null, null),
  ('cus-cyl-grav-mat', 'Matériau de la gravure du cylindre', 'Personnalisation', 1.25, null, null),
  ('cus-poignee', 'Poignée', 'Personnalisation', 1.25, null, null),
  ('cus-poignee-grav', 'Gravure de la poignée', 'Personnalisation', 1.25, null, null),
  ('cus-crosse-teinte', 'Teinte de la crosse', 'Personnalisation', 1.25, null, null),
  ('cus-detente-mat', 'Matériau de la détente', 'Personnalisation', 1.25, null, null),
  ('cus-cadre', 'Cadre', 'Personnalisation', 1.25, null, null),
  ('cus-emballage', 'Emballage', 'Personnalisation', 1.25, null, null),
  ('cus-emballage-mat', 'Matériau de l''emballage', 'Personnalisation', 1.25, null, null),
  ('cus-emballage-teinte', 'Teinte de l''emballage', 'Personnalisation', 1.25, null, null),
  ('cus-chargeur', 'Chargeur', 'Personnalisation', 1.25, null, null)
on conflict (id) do update set name = excluded.name, category = excluded.category, price = excluded.price,
  stock = null, image = excluded.image;
